#!/bin/bash

command -v log-run   >/dev/null 2>&1 || source "$(command -v logshell    2>/dev/null || echo "$(dirname "${BASH_SOURCE[0]}")/logshell")"
command -v checkOsID >/dev/null 2>&1 || source "$(command -v checksystem 2>/dev/null || echo "$(dirname "${BASH_SOURCE[0]}")/checksystem")"

checkPcidev() {
  local dev="${1}"
  lspci -s "${dev}" -v
}

# check base on devid
checkUsbdev() {
  local devid="${1}"
  lsusb -v -d "${devid}"
}

kmod_unload() {
  local module="${1}"
  modprobe -r "${module}"
}

kmod_blacklist() {
  local module="${1}"
  [ ! -e /etc/modprobe.d/"${module}".conf ] && {
    echo "blacklist ${module}" >/etc/modprobe.d/"${module}".conf
  } || {
    [[ $(checkIfFileHaveText "blacklist ${module}" "/etc/modprobe.d/${module}.conf") == "yes" ]] && {
      echo "Black list file for this module already exist"
    } || {
      echo "blacklist ${module}" >>/etc/modprobe.d/"${module}".conf
    }
  }
}

systemd_listservice() {
  systemctl list-units --type=service
}

systemd_listtarget() {
  systemctl list-units --type=target
}

# suspend, hibernate
openConfigPowerFile() {
  nano /etc/systemd/logind.conf
}

openSystemdServiceConfigDir() {
  cd /lib/systemd/system || return 1
}

# need usb live, and alreaady mount /dev/sda1 to /mnt/tmp (for example is boot partitiion of disk need fix)
grubReInstall() {
  grub-install --boot-directory=/mnt/tmp /dev/sda
}

# Booting from the GRUB 2 Shell
fixmisconfigGrub() {
  #set root=(hd0,msdos1)
  #linux /vmlinuz root=/dev/sda1
  #initrd /initrd.img
  echo "Booting from the GRUB 2 Shell"
}

# Booting from the Rescue Shell
fixmisconfigGrub_RescueShell() {
  #set prefix=(hd0,msdos1)/boot/grub
  #insmod normal
  #insmod linux

  #set root=(hd0,msdos1)
  #linux /vmlinuz root=/dev/sda1
  #initrd /initrd.img
  echo "Booting from the Rescue Shell"
}

findPartitionUUID() {
  ls -la /dev/disk/by-uuid/
}

# run after change config file of liker (ld)
updateLdConfig() {
  ldconfig
}

addTempLdPath() {
  export LD_LIBRARY_PATH="${1}"
}

# lib/x86_64-linux-gnu/libc.so.6 or /bin/bash
findDependencyOfBinaryofObjectFile() {
  objdump -p "${1}" | grep NEEDED
}
